#!/bin/sh

if [ -d "$HOME/sec/ssh" ]
then
  [ ! -d "$dot_root/.ssh" ] && mkdir "$dot_root/.ssh"
  for f in "$HOME"/sec/ssh/*
  do
    fn=$(basename $f)
    [ ! -e "$dot_root/.ssh/$fn" ] && ln -s $f $dot_root/.ssh/$fn
  done
fi

if [ -f "$HOME/sec/scripts/sign.py" ]
then
  [ ! -d "$dot_root/.bash.d/bin" ] && mkdir -p "$dot_root/.bash.d/bin"
  ln -s "$HOME/sec/scripts/sign.py" "$dot_root/.bash.d/bin/sign.py"
fi

exit 0
