#!/bin/sh

for d in "$dot_root/.emacs.d/share/emacs/site-lisp" "$dot_root/.emacs.d/libexec/emacs/site-start.d"
do
  test -d "$d" || mkdir -p $d
done
exec make -C data/magit.git all PREFIX="$dot_root/.emacs.d" SYSCONFDIR="$dot_root/.emacs.d/libexec"
