(require 'erc)
(require 'erc-join)
(require 'erc-match)
(require 'erc-track)
(require 'erc-fill)
(require 'erc-ring)
(require 'erc-netsplit)

(load "~/.erc.passwd")

(setq erc-keywords '("dsouza"))
(setq erc-log-insert-log-on-open nil)
(setq erc-log-channels t)
(setq erc-log-channels-directory "~/.irclogs/")
(setq erc-save-buffer-on-part t)
(setq erc-hide-timestamps nil)
(setq erc-max-buffer-size 20000)
(setq erc-truncate-buffer-on-save t)
(setq erc-email-userid "dsouza@bitforest.org")
(setq erc-prompt-for-nickserv-password nil)
(setq erc-timestamp-format "[%R-%m/%d]")
(setq erc-autojoin-channels-alist
          '(("freenode" "#haskell" "#agda" "#latex" "#emacs" "##devel-pedreiro" "#guru-sp")
            ("locaweb" "#cloud" "#infradev")))

(add-hook 'erc-insert-post-hook 'erc-save-buffer-in-logs)
(add-hook 'erc-insert-post-hook 'erc-truncate-buffer)
(add-hook 'erc-after-connect '(lambda (SERVER NICK)
                                (message server)
                                (erc-message "PRIVMSG" (concat "nickserv identify dsouza " nickserv-passwd))))

(erc-match-mode t)
(erc-autojoin-mode t)
(erc-track-mode t) 
(erc-fill-mode t)
(erc-ring-mode t)
(erc-netsplit-mode t)
(erc-timestamp-mode t)
(erc-button-mode (- 1))

;; Reference: http://www.emacswiki.org/emacs/ErcStartupFiles
(defun my-irc ()
   "Start to waste time on IRC with ERC."
   (interactive)
   (erc :server "irc.freenode.net" :port 6667 :nick "dsouza" :full-name "Diego Souza")
   (when (y-or-n-p "Bitlbee? ")
     (erc :server "localhost" :port 6667 :nick "dsouza" :full-name "Diego Souza"))
   (when (y-or-n-p "Locaweb? ")
     (erc :server "irc.linux.locaweb.com.br" :port 6667 :nick "dsouza" :full-name "Diego Souza"))
   )

