#!/bin/bash

fg_norm_black='[22;30m'
bg_norm_black='[22;40m'
fg_bold_black='[01;30m'
bg_bold_black='[01;40m'

fg_norm_grey=$fg_norm_black
bg_norm_black=$bg_norm_black
fg_bold_grey=$fg_bold_black
bg_bold_black=$bg_bold_black

fg_norm_red='[22;31m'
bg_norm_red='[22;41m'
fg_bold_red='[01;31m'
bg_bold_red='[01;41m'

fg_norm_magenta='[22;35m'
bg_norm_magenta='[22;45m'
fg_bold_magenta='[01;35m'
bg_bold_magenta='[01;45m'

fg_norm_green='[22;32m'
bg_norm_green='[22;42m'
fg_bold_green='[01;32m'
bg_bold_green='[01;42m'

fg_norm_yellow='[22;33m'
bg_norm_yellow='[22;43m'
fg_bold_yellow='[01;33m'
bg_bold_yellow='[01;43m'

fg_norm_blue='[22;34m'
bg_norm_blue='[22;44m'
fg_bold_blue='[01;34m'
bg_bold_blue='[01;44m'

fg_norm_cyan='[22;36m'
bg_norm_cyan='[22;46m'
fg_bold_cyan='[01;36m'
bg_bold_cyan='[01;46m'

fg_norm_white='[22;37m'
bg_norm_white='[22;47m'
fg_bold_white='[01;37m'
bg_bold_white='[01;47m'

fg_norm_def='[22;39m'
bg_norm_def='[22;49m'
fg_bold_def='[01;39m'
bg_bold_def='[01;49m'

nocolors='[0m'

my_test_interactive ()
{
  [[ $- == *i* ]]
}

my_test_root ()
{
  test "$EUID" -eq 0
}

my_setenv()
{
  export PAGER=/usr/bin/less
  export GPG_TTY=$(/usr/bin/tty)
  export LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
  if my_test_root; then
    PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  else
    PATH="/usr/local/bin:/usr/bin:/bin"
  fi
  PATH="$PATH:/usr/bin/vendor_perl"
  if my_test_interactive
  then
    export PS1="\[$fg_bold_red\]➜ \[$fg_bold_grey\]|\\u@\\H| \[$fg_norm_cyan\]\\w \\n\[$fg_bold_yellow\]\\$\[$nocolors\] "
  fi
  export HISTFILE=$HOME/.bash_history
  export HISTFILESIZE=10000
  export HISTSIZE=7500
  export HISTCONTROL=ignoredups:erasedups
  export HISTIGNORE=" *"
  export PATH
}
