#!/bin/sh

has_x11 ()
{
  test -n "$DISPLAY"
}

has_emacsclient ()
{
  emacsclient -e "nil" 2>/dev/null >/dev/null
}

has_emacs ()
{
  command -V emacs 2>/dev/null >/dev/null
}

has_gvim ()
{
  command -V gvim 2>/dev/null >/dev/null
}

has_vim ()
{
  command -V vim 2>/dev/null >/dev/null
}

has_vi ()
{
  command -V vi 2>/dev/null >/dev/null
}

has_x11 && has_emacsclient && exec emacsclient -c "$@"
has_emacsclient            && exec emacsclient -nw "$@"
has_emacs                  && exec emacs "$@"
has_x11 && has_gvim        && exec gvim "$@"
has_vim                    && exec vim "$@"
has_vi                     && exec vi "$@"
exit -1
