#!/bin/sh

has_x11 ()
{
  test -n "$DISPLAY"
}

has_emacsclient ()
{
  emacsclient -e "nil" 2>/dev/null >/dev/null
}

has_emacs ()
{
  command -v emacs 2>/dev/null >/dev/null
}

has_gvim ()
{
  command -v gvim 2>/dev/null >/dev/null
}

has_vim ()
{
  command -v vim 2>/dev/null >/dev/null
}

has_vi ()
{
  command -v vi 2>/dev/null >/dev/null
}

has_x11 && has_emacsclient && exec my-gpg-env emacsclient -c "$@"
has_emacsclient            && exec my-gpg-env emacsclient -nw "$@"
has_emacs                  && exec my-gpg-env emacs "$@"
has_x11 && has_gvim        && exec gvim "$@"
has_vim                    && exec vim "$@"
has_vi                     && exec vi "$@"
exit -1
