#!/bin/bash
# -*- mode: Shell-script; sh-basic-offset: 2; -*-

test -r /etc/bash.bashrc                           && . /etc/bash.bashrc
test -r /etc/bashrc                                && . /etc/bashrc
test -r /usr/share/bash-completion/bash_completion && . /usr/share/bash-completion/bash_completion

. $HOME/.bash.d/functions

my_setenv

if ls --color >/dev/null 2>/dev/null
then
  if which ls >/dev/null 2>/dev/null
  then
    alias ls="$(which ls) --color"
  fi
fi

if echo x | grep --color . >/dev/null 2>/dev/null
then
  if which grep >/dev/null 2>/dev/null
  then
    alias grep="$(which grep) --color"
  fi
fi
alias ll="ls -l"
alias l1="ls -1"
alias la="ll -a"
alias rm="/bin/rm -i"

shopt -s histappend
shopt -s extglob
shopt -s extquote
shopt -s cdspell
shopt -s dirspell
shopt -s globstar
shopt -s checkjobs
shopt -s checkwinsize

for f in $HOME/.bash.d/include.d/*.sh
do
  . $f
done

#my_test_interactive && {
#  my_encfs
#  if [ -z "$SSH_CONNECTION" ]
#  then
#    my_gpgagent_cleanse
#    my_gpgagent_init
#    my_gpgagent_export
#  fi
#}
