#!/bin/sh

if [ -d "$HOME/sec/ssh" ]
then
  [ ! -d "$dot_root/.ssh" ] && mkdir "$dot_root/.ssh"
  for f in "$HOME"/sec/ssh/*
  do
    fn=$(basename $f)
    [ ! -e "$dot_root/.ssh/$fn" ] && ln -s $f $dot_root/.ssh/$fn
  done
fi
