#!/bin/bash
# -*- mode: Shell-script; sh-basic-offset: 2; -*-

. $HOME/.bash.d/functions

my_setenv

if ls --color >/dev/null 2>/dev/null
then
  if command -v ls >/dev/null 2>/dev/null
  then
    alias ls="$(which ls) --color"
  fi
fi

if echo x | grep --color . >/dev/null 2>/dev/null
then
  if command -v grep >/dev/null 2>/dev/null
  then
    alias grep="$(which grep) --color"
  fi
fi
alias ll="ls -l"
alias l1="ls -1"
alias la="ll -a"
alias rm="/bin/rm -i"
alias oterm="env TERM=rxvt"

shopt -s histappend
shopt -s extglob
shopt -s extquote
shopt -s cdspell
shopt -s dirspell
shopt -s globstar
shopt -s checkjobs
shopt -s checkwinsize

for f in "$HOME"/.bash.d/include.d/**/*
do
  [ -f "$f" -a -r "$f" ] && . $f
done

for d in "$HOME"/.bash.d/bin/**/
do
  PATH="$PATH:$d"
done

PATH="$PATH:$HOME/.bin"
export PATH
