---

- hosts: localhost
  connection: local

  vars:
    - root: "{{ dx15_root | default(ansible_env.HOME) }}"
    - clean: "{{ dx15_clean | default(false) }}"

  pre_tasks:
    - name: create temporary directory
      tempfile:
        state: directory
      register: tempdir
      changed_when: false

  roles:
    - role: system
      tags: [system]
      vars:
        locale: en_US.UTF-8
        timezone: America/Sao_Paulo
    - role: bash
      tags: [bash]
      cwd: "{{ playbook_dir }}/roles/bash"
    - role: emacs
      tags: [emacs]
      cwd: "{{ playbook_dir }}/roles/emacs"
    - role: apps
      tags: [apps]
      cwd: "{{ playbook_dir }}/roles/apps"

  post_tasks:
    - name: remove temporary directory
      file:
        path: "{{ tempdir.path }}"
        state: absent
      changed_when: false
