#!/bin/bash
# -*- mode: Shell-script; sh-basic-offset: 2; -*-

test -r /etc/profile && . /etc/profile

. $HOME/.bash.d/functions

my_setenv

shopt -s globstar

for f in $HOME/.bash.d/profile.d/**/*
do
  [ -f "$f" -a -r "$f" ] && . $f
done

test -r "$HOME/.bashrc" && . "$HOME/.bashrc"
