#!/bin/bash
# -*- mode: Shell-script; sh-basic-offset: 2; -*-

. $HOME/.bash.d/functions

my_setenv

if ls --color >/dev/null 2>/dev/null
then
  if command -v ls >/dev/null 2>/dev/null
  then
    alias ls="$(which ls) --color"
  fi
fi

if echo x | grep --color . >/dev/null 2>/dev/null
then
  if command -v grep >/dev/null 2>/dev/null
  then
    alias grep="$(which grep) --color"
  fi
fi
alias ll="ls -l"
alias l1="ls -1"
alias la="ll -a"
alias rm="/bin/rm -i"

shopt -s histappend
shopt -s extglob
shopt -s extquote
shopt -s cdspell
shopt -s dirspell
shopt -s globstar
shopt -s checkjobs
shopt -s checkwinsize

bind -m emacs -x '"\C-k": my_kill_whole_line'
bind -m emacs -x '"\C-\M-k": my_kill_line'
bind -m emacs -x '"\C-x\C-?": my_backward_kill_line'
bind -m emacs -x '"\C-y": my_x11_yank'

for f in "$HOME"/.bash.d/include.d/**/*
do
  [ -f "$f" -a -r "$f" ] && . $f
done

for d in "$HOME"/.bash.d/bin/**/
do
  export PATH="$PATH:$d"
done
